@startuml
Class Game {
    id: long
    gameState: GameState
    bugHealth: int
    level: int
}

class Player {
    game: long
    name: string
    color: Color
    score: int
    isReady: boolean
    isAlive: boolean
    hasLeft: boolean
}

Game "1" *-- "1..n" Player
@enduml